presubmits:
  ginbits/tanqueray:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-tanqueray-master-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/var/tmp/commitlint/commitlint.config.js
        - --from=$(PULL_BASE_SHA)
        - --to=$(PULL_PULL_SHA)
        command:
        - commitlint
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
        volumeMounts:
        - name: commitlint-config
          mountPath: /var/tmp/commitlint
      volumes:
      - name: commitlint-config
        configMap:
          name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/markdownlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-tanqueray-master-markdownlint
    rerun_command: /test markdownlint
    spec:
      containers:
      - args:
        - -v
        - -w
        - -a
        - .
        command:
        - mdl
        image: pipelinecomponents/markdownlint
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )markdownlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/dotenv-linter
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-tanqueray-master-dotenv-linter
    rerun_command: /test dotenv-linter
    spec:
      containers:
      - command:
        - dotenv-linter
        image: dotenvlinter/dotenv-linter:latest
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )dotenv-linter,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/stylelint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-tanqueray-master-stylelint
    rerun_command: /test stylelint
    spec:
      containers:
      - args:
        - --color
        - '**/*.css'
        command:
        - stylelint
        image: pipeline-components/stylelint:latest
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )stylelint,?($|\s.*)
