presubmits:
  ginbits/release:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/var/tmp/commitlint/commitlint.config.js
        - --from=$(PULL_BASE_SHA)
        - --to=$(PULL_PULL_SHA)
        command:
        - commitlint
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
        volumeMounts:
        - name: commitlint-config
          mountPath: /var/tmp/commitlint
      volumes:
      - name: commitlint-config
        configMap:
          name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/yamllint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-yamllint
    rerun_command: /test yamllint
    spec:
      containers:
      - args:
        - -c
        - services/yamllint/yamllint.conf
        - config
        - cluster
        command:
        - yamllint
        image: quay.io/kubermatic/yamllint:0.1
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )yamllint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/markdownlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-markdownlint
    rerun_command: /test markdownlint
    spec:
      containers:
      - args:
        - -v
        - -w
        - -a
        - .
        command:
        - mdl
        image: pipelinecomponents/markdownlint
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )markdownlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/config
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-config
    rerun_command: /test config
    spec:
      containers:
      - args:
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        - --config-path=./services/prow/config.yaml
        - --job-config-path=./config/jobs/
        - --plugin-config=./services/prow/plugins.yaml
        - --strict
        command:
        - /checkconfig
        image: gcr.io/k8s-prow/checkconfig:v20220115-3e20513bd7
        imagePullPolicy: IfNotPresent
        name: ""
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
    trigger: (?m)^/test( | .* )config,?($|\s.*)
