base_images:
  os:
    name: centos
    namespace: origin
    tag: stream8
binary_build_commands: make production-install
build_root:
  from_repository: true
  use_build_cache: true
images:
- context_dir: images/ci-operator/
  from: os
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/bin/ci-operator
  to: ci-operator
promotion:
  namespace: ci
  tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: make race-install
zz_generated_metadata:
  branch: master
  org: openshift
  repo: ci-tools
