presubmits:
  ginbits/ginsul:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-ginsul-master-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/var/tmp/commitlint/commitlint.config.js
        - --from=$(PULL_BASE_SHA)
        - --to=$(PULL_PULL_SHA)
        command:
        - commitlint
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
        volumeMounts:
        - name: commitlint-config
          mountPath: /var/tmp/commitlint
      volumes:
      - name: commitlint-config
        configMap:
          name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/eslint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-ginsul-master-eslint
    rerun_command: /test eslint
    spec:
      containers:
      - image: rhuan/react-lint
        args:
          - .
        command:
        - eslint
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )eslint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/hadolint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-ginsul-development-hadolint
    rerun_command: /test hadolint
    spec:
      containers:
      - image: hadolint/hadolint
        imagePullPolicy: Always
        command:
        - hadolint
        args:
        - --verbose
    trigger: (?m)^/test( | .* )hadolint,?($|\s.*)
