orgs:
  ginbits:
    labels:
      - color: 0ffa16
        description: Indicates a PR has been approved by an approver from all required OWNERS files.
        name: approved
        target: prs
        prowPlugin: approve
        addedBy: approvers
      - color: e11d21
        description: Indicates that a PR should not merge because someone has issued a /hold command.
        name: do-not-merge/hold
        target: prs
        prowPlugin: hold
        addedBy: anyone
      - color: e11d21
        description: Indicates that a PR should not merge because it has an invalid OWNERS file in it.
        name: do-not-merge/invalid-owners-file
        target: prs
        prowPlugin: verify-owners
        addedBy: prow
      - color: e11d21
        description: Indicates that a PR should not merge because it's missing one of the release note labels.
        name: do-not-merge/release-note-label-needed
        previously:
          - name: release-note-label-needed
        target: prs
        prowPlugin: releasenote
        addedBy: prow
      - color: e11d21
        description: Indicates that a PR should not merge because it is a work in progress.
        name: do-not-merge/work-in-progress
        target: prs
        prowPlugin: wip
        addedBy: prow
      - color: e11d21
        description: Categorizes issue or PR as related to adding, removing, or otherwise changing an API
        name: kind/api-change
        previously:
          - name: kind/new-api
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: e11d21
        description: Categorizes issue or PR as related to a bug.
        name: kind/bug
        previously:
          - name: bug
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 1de1c8
        description: Categorizes issue or PR as related to changing dependencies
        name: kind/dependency-change
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to cleaning up code, process, or technical debt.
        name: kind/cleanup
        previously:
          - name: kind/friction
          - name: kind/technical-debt
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to design.
        name: kind/design
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to documentation.
        name: kind/documentation
        previously:
          - name: kind/old-docs
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: e11d21
        description: Categorizes issue or PR as related to a consistently or frequently failing test.
        name: kind/failing-test
        previously:
          - name: priority/failing-test
          - name: kind/e2e-test-failure
          - name: kind/upgrade-test-failure
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to a new feature.
        name: kind/feature
        previously:
          - name: enhancement
          - name: kind/enhancement
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: f7c6c7
        description: Categorizes issue or PR as related to a flaky test.
        name: kind/flake
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 15dd18
        description: Indicates that a PR is ready to be merged.
        name: lgtm
        target: prs
        prowPlugin: lgtm
        addedBy: reviewers or members
      - color: BDBDBD
        description: Indicates a PR cannot be merged because it has merge conflicts with HEAD.
        name: needs-rebase
        target: prs
        prowPlugin: needs-rebase
        addedBy: prow
      - color: 15dd18
        description: Indicates a non-member PR verified by an org member that is safe to test.
        name: ok-to-test
        target: prs
        prowPlugin: trigger
        addedBy: prow
      - color: fef2c0
        description: Lowest priority. Possibly useful, but not yet enough support to actually get it done.
        name: priority/awaiting-more-evidence
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: fbca04
        description: Higher priority than priority/awaiting-more-evidence.
        name: priority/backlog
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: e11d21
        description: Highest priority. Must be actively worked on as someone's top priority right now.
        name: priority/critical-urgent
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: eb6420
        description: Important over the long term, but may not be staffed and/or may need multiple releases to complete.
        name: priority/important-longterm
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: eb6420
        description: Must be staffed and worked on either currently, or very soon, ideally in time for the next release.
        name: priority/important-soon
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: ee9900
        description: Denotes a PR that changes 100-499 lines, ignoring generated files.
        name: size/L
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: eebb00
        description: Denotes a PR that changes 30-99 lines, ignoring generated files.
        name: size/M
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: 77bb00
        description: Denotes a PR that changes 10-29 lines, ignoring generated files.
        name: size/S
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: ee5500
        description: Denotes a PR that changes 500-999 lines, ignoring generated files.
        name: size/XL
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: "009900"
        description: Denotes a PR that changes 0-9 lines, ignoring generated files.
        name: size/XS
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: ee0000
        description: Denotes a PR that changes 1000+ lines, ignoring generated files.
        name: size/XXL
        target: prs
        prowPlugin: size
        addedBy: prow
      - color: ffaa00
        description: Denotes a PR that should be squashed by tide when it merges.
        name: tide/merge-method-squash
        target: prs
        addedBy: humans
        previously:
          - name: tide/squash
      - color: ffaa00
        description: Denotes a PR that should be rebased by tide when it merges.
        name: tide/merge-method-rebase
        target: prs
        addedBy: humans
      - color: ffaa00
        description: Denotes a PR that should use a standard merge by tide when it merges.
        name: tide/merge-method-merge
        target: prs
        addedBy: humans
      - color: e11d21
        description: Denotes an issue that blocks the tide merge queue for a branch while it is open.
        name: tide/merge-blocker
        target: issues
        addedBy: humans
      - color: f9d0c4
        description: ¯\\\_(ツ)_/¯
        name: "¯\\_(ツ)_/¯"
        target: both
        prowPlugin: shrug
        addedBy: humans
