apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-wowpotjackpot-org
  namespace: affwebsites
  labels:
    deployer.ginbits.com/org: ginbits
    deployer.ginbits.com/repo: bloom
    deployer.ginbits.com/branch: master
    deployer.ginbits.com/image: cms.wowpotjackpot.org
    domain: cms.wowpotjackpot.org
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: cms.wowpotjackpot.org
  template:
    metadata:
      labels:
        domain: cms.wowpotjackpot.org
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: website
        image: ghcr.io/ginbits/bloom/cms.wowpotjackpot.org:master
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/www/html/.env
          name: cms-wowpotjackpot-org-env
          subPath: .env
        - mountPath: /var/www/html/auth.json
          name: composer-creds
          subPath: auth.json
      volumes:
      - name: cms-wowpotjackpot-org-env
        secret:
          secretName: cms-wowpotjackpot-org-env
      - name: composer-creds
        secret:
          secretName: composer-creds
---
apiVersion: v1
kind: Service
metadata:
  name: cms-wowpotjackpot-org
  namespace: affwebsites
spec:
  selector:
    domain: cms.wowpotjackpot.org
  ports:
  - name: http
    port: 8080
    protocol: TCP
  type: NodePort
