presubmits:
  ginbits/hendricks:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/var/tmp/commitlint/commitlint.config.js
        - --from=$(PULL_BASE_SHA)
        - --to=$(PULL_PULL_SHA)
        command:
        - commitlint
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
        volumeMounts:
        - name: commitlint-config
          mountPath: /var/tmp/commitlint
      volumes:
      - name: commitlint-config
        configMap:
          name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/phpcsfixer
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-phpcsfixer
    rerun_command: /test php-cs-fixer
    spec:
      containers:
      - args:
        - fix
        - -vvv
        - --diff
        - --dry-run
        - --no-ansi
        - --no-interaction
        - --using-cache=no
        command:
        - php-cs-fixer
        image: wiseartisans/php-cs-fixer:2
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )php-cs-fixer,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/phpunit
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-phpunit
    rerun_command: /test phpunit
    spec:
      containers:
      - command:
        - ./scripts/phpunit.sh
        image: jitesoft/phpunit:7.4
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )phpunit,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/phpmd
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-phpmd
    rerun_command: /test phpmd
    spec:
      containers:
      - args:
        - app/
        - ansi
        - phpmd_rulesets.xml
        command:
        - phpmd
        image: elnebuloso/php-phpmd:latest
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )phpmd,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/phpcpd
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-phpcpd
    rerun_command: /test phpcpd
    spec:
      containers:
      - args:
        - --min-lines=30
        - --verbose
        - app/
        command:
        - phpcpd
        image: ajardin/phpcpd:latest
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )phpcpd,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/markdownlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-master-markdownlint
    rerun_command: /test markdownlint
    spec:
      containers:
      - args:
        - -v
        - -w
        - -a
        - .
        command:
        - mdl
        image: pipelinecomponents/markdownlint
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )markdownlint,?($|\s.*)
