presubmits:
  ginbits/hendricks:
  - agent: kubernetes
    always_run: true
    branches:
    - staging
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-staging-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/var/tmp/commitlint/commitlint.config.js
        - --from=$(PULL_BASE_SHA)
        - --to=$(PULL_PULL_SHA)
        command:
        - commitlint
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
        volumeMounts:
        - name: commitlint-config
          mountPath: /var/tmp/commitlint
      volumes:
      - name: commitlint-config
        configMap:
          name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - staging
    context: ci/prow/phpcsfixer
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-staging-phpcsfixer
    rerun_command: /test php-cs-fixer
    spec:
      containers:
      - args:
        - fix
        - -vvv
        - --diff
        - --dry-run
        - --no-ansi
        - --no-interaction
        - --using-cache=no
        command:
        - php-cs-fixer
        image: wiseartisans/php-cs-fixer:2
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )php-cs-fixer,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - staging
    context: ci/prow/phpunit
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-hendricks-staging-phpunit
    rerun_command: /test phpunit
    spec:
      containers:
      - args:
        - phpunit
        command:
        - make
        image: jitesoft/phpunit:7.4
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )phpunit,?($|\s.*)
