presubmits:
  ginbits/infra-controllers:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/unit
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-unit
    rerun_command: /test unit
    spec:
      containers:
      - args:
        - unit
        command:
        - make
        image: golang:1.17.1
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/lint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-lint
    rerun_command: /test lint
    spec:
      containers:
      - args:
        - lint
        command:
        - make
        image: golangci/golangci-lint:v1.42
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )lint,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/commitlint
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-commitlint
    rerun_command: /test commitlint
    spec:
      containers:
      - args:
        - --config=/etc/commitlint/commitlint.config.js
        - --from=HEAD~$(git --no-pager rev-list master..HEAD --count)
        image: gtramontina/commitlint:8.3.5
        imagePullPolicy: Always
      volumeMounts:
      - name: commitlint-config
        mountPath: /etc/commitlint
        readOnly: true
    volumes:
    - name: commitlint-config
      configMap:
        name: commitlint-config
    trigger: (?m)^/test( | .* )commitlint,?($|\s.*)
