presubmits:
  ginbits/infra-controllers:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/unit
    decorate: true
    decoration_config:
      oauth_token_secret:
        key: oauth
        name: github-cloner
    name: pull-ci-ginbits-release-master-unit
    rerun_command: /test unit
    spec:
      containers:
      - args:
        - test
        command:
        - make
        image: centos:7
        imagePullPolicy: Always
    trigger: (?m)^/test( | .* )unit,?($|\s.*)